### ISSUE TITLE
TOTP Life time

### ISSUE THREAD

**Issue by selvakumar89** [multiOTP/multiotp#11]
Hi,
I have generated the following 6 digit TOTP'S 
at = 5:45:30PM - 310114
at = 5:55:00PM - 973270
at = 5:55:30PM - 997680

Now (5:55:30PM) I do verifyOTP with 310114 which was generated at 5:45:30PM I am getting verification success (code 0). At this moment (5:55:30PM) my OTP is 997680 but if I try my previous OTP's I am getting success why?
Do we need to change anything in config or I am doing anything wrong here. Please explain me.
What is the life time for this TOTP's?

Thanks.

**Comment by multiOTP** [comment]
Hello,
As stated in the TOTP OATH definition, a specific "time window" must accept not well synchronized tokens.
This is safe, as the OTP cannot be played again, and it's also not possible to play an older (played or not) OTP older than the last one played.
The calculation of the time difference between the token and the server is done and saved automatically for the concerned user at every successful connection.

By default, the time window is set to 600 seconds (10 minutes). You can adjust this value:
- in the multiotp.ini file (max_time_window=xxx)
- by command-line: multiotp.php -config max-time-window=xxx

Be careful, as some hardware tokens can deviate from several seconds per months.

If you are too much desynchronized and your OTP is refused, you can resynhronize automatically the token by sending
**[prefix if needed][OTP(n)][SPACE][OTP(n+1)]**
instead of
**[prefix if needed][OTP(n)]**

Regards,

**Comment by selvakumar89** [comment]
Hi,
Thank you for the prompt response.
I can change the max-time-window. 
I changed into 300 it is working fine. If change into 60sec my OTP getting failed.
Can't we set the window 30sec or 60sec?

**Comment by multiOTP** [comment]
Hello,
max-time-window can be any value, but if the time difference between the token device and the server is for example two minutes, you need to put at least max-time-window=130 (to have the opportunity to match the code that was calculated 130 seconds before on the server side).
