### ISSUE TITLE
"Windows username or password incorrect" when using credential provider client

### ISSUE THREAD

**Issue by tmontney** [multiOTP/multiotp#110]
New install, used the raspberry pi distro, following the text file instructions. Configured AD via https://github.com/multiOTP/multiotp. Using the credential provider from this same repo.

I believe I'm doing something wrong with the client.

I was seeing the same message in the log until I set `default-request-prefix-pin` to 0 and resynced users. Now I see `ERROR: Authentication failed (wrong token length)`. I'm no longer seeing attempts against my DC and my user in the web GUI is not locked out.

**Comment by multiOTP** [comment]
Hello,

Using multiOTP open source, the "default-request-prefix-pin" is the default value that will be used for the "request-prefix-pin" value option for newly created users.

If you are using multIOTP open source with multiOTP Credential Provider, the best configuration is to set the request-prefix-pin to 0, as the first factor is already done by the Microsoft authentication.

multiOTP Credential Provider must also be configured accordingly, otherwise multiOTP open source will still receive the concatenation pf the Microsoft username and the 2FA token. This is probably why the log says "wrong token length", because multiOTP open source receives a too long token (microsoft password + token, instead of token only).

Regards,
