### ISSUE TITLE
Upgrade Virtual appliance v5.6.1.5 to 5.8.2.9 - warning messages

### ISSUE THREAD

**Issue by NazZaR** [multiOTP/multiotp#114]
Hello.
We are trying to upgrade our virtual appliance v5.6.1.5 ([downloaded from here](https://download.multiotp.net/ova/multiotp-open-source-vm-009-5.6.1.5.ova)) to version v5.8.2.9.
Since there is no updated OVA, we have downloaded full v5.8.2.9 package, and tried to upgrade. 
Readme says:
```
If you are currently using the multiOTP open source Virtual Appliance, you can upgrade
the multiOTP version by copying the extracted content of the folder and subfolders from
raspberry/boot-part/multiotp-tree/usr/local/bin/multiotp to /usr/local/bin/multiotp  
```
So we did that and it seems that service is now working. 
Here is journalctl -ex output after systemctl start multiotp:
```
Nov 23 16:31:47 multiotp systemd[1]: Started Initialize the multiOTP functionalities.
-- Subject: A start job for unit multiotp.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit multiotp.service has finished successfully.
-- 
-- The job identifier is 2451.
Nov 23 16:31:47 multiotp multiotp-service.sh[2846]: /usr/local/bin/multiotp/scripts/multiotp-service.sh: line 212: i2cdetect: command not found
Nov 23 16:31:47 multiotp multiotp-service.sh[2846]: /usr/local/bin/multiotp/scripts/multiotp-service.sh: line 220: i2cdetect: command not found
Nov 23 16:31:47 multiotp multiotp-service.sh[2846]: /usr/local/bin/multiotp/scripts/multiotp-service.sh: line 226: i2cdetect: command not found
Nov 23 16:31:47 multiotp multiotp-service.sh[2846]: /usr/local/bin/multiotp/scripts/multiotp-service.sh: line 233: i2cdetect: command not found
Nov 23 16:31:47 multiotp systemd[1]: multiotp.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit multiotp.service has successfully entered the 'dead' state.
```
What are we doing wrong? Maybe, version gap is too big?
Thank you in advance!

**Comment by MovingLightShow** [comment]
Hello,

No, sorry for that, these warnings are displayed because the system detect if any i2c devices are available (like a real-time clock), but this is useful for micro-computers like Raspberry Pi.

The i2cdetect utility is by default not available in a standard distribution.

Don't worry about these warnings, and thanks for the feedback, we will detect and remove the call to i2cdetect if not needed for the used plateform in the next release.

Regards,

**Comment by multiOTP** [comment]
Hello,

No, sorry for that, these warnings are displayed because the system detect if any i2c devices are available (like a real-time clock), but this is useful for micro-computers like Raspberry Pi.

The i2cdetect utility is by default not available in a standard distribution.

Don't worry about these warnings, and thanks for the feedback, we will detect and remove the call to i2cdetect if not needed for the used plateform in the next release.

Regards,

**Comment by NazZaR** [comment]
> Hello,
> 
> No, sorry for that, these warnings are displayed because the system detect if any i2c devices are available (like a real-time clock), but this is useful for micro-computers like Raspberry Pi.
> 
> The i2cdetect utility is by default not available in a standard distribution.
> 
> Don't worry about these warnings, and thanks for the feedback, we will detect and remove the call to i2cdetect if not needed for the used plateform in the next release.
> 
> Regards,

Sorry, I meant to write 'service not working' above, don't know how I did that typo 😅
Multiotp does not start after upgrade.

**Comment by NazZaR** [comment]
@multiOTP , please assist

**Comment by multiOTP** [comment]
Hello NazZaR,
We will provide a full set of new virtual appliance for the (very) end of this year.
It will be based on the 5.9.x version of multiOTP, and the underlying OS will be the last 11.x version of Debian (bullseye).
Regards,

**Comment by NazZaR** [comment]
@multiOTP , thank you!

**Comment by NazZaR** [comment]
@multiOTP , hello. Please, is there an update available?

**Comment by multiOTP** [comment]
Hello,
Open source version 5.8.7.0 is yet publicly available, which is the base of the next virtual appliance.
Final tests of the next virtual appliance are on the way.
Regards,
