### ISSUE TITLE
User description under QR code

### ISSUE THREAD

**Issue by NazZaR** [multiOTP/multiotp#129]
Hello.
Is it intended that user description appears under QR code, rather than username? When description is empty, username appears instead.
![image](https://user-images.githubusercontent.com/5753530/172332022-eeef2da7-5dfa-434c-8002-9711fc9c0141.png)

**Comment by multiOTP** [comment]
Hello,

The URL inside the QR code need a description in order to display it in the OTP generator. Therefore, multiOTP is looking for the best description possible.
If description is not existing, the username is used instead.

If you want always to display the username under the QR code, please modify the template.html file from `<td class="account">{MultiotpUserDescription}</td>` to `<td class="account">{MultiotpUserAccount}</td>`

If you want also to change the description in the URL inside the QR code, this is now also possible since 5.9.0.3. Modify the template.html file from `<td>{MultiotpQrCodeUserToken account=MultiotpUserDescription width=250 height=250}</td>` to `<td>{MultiotpQrCodeUserToken account=MultiotpUserAccount width=250 height=250}</td>`

Regards,

**Comment by NazZaR** [comment]
Great, thank you!
