### ISSUE TITLE
Client-Server issue : warning System Error: database file C:\Program Files (x86)\multiOTP\.\users\ppetrov.db for user ppetrov does not exist

### ISSUE THREAD

**Issue by ejikoff** [multiOTP/multiotp#143]
Hello.
Authorization problem.
```
C:\Program Files (x86)\multiOTP>multiotp.exe -display-log -log -debug ppetrov 043802
LOG 2022-10-27 06:02:51 warning System Error: database file C:\Program Files (x86)\multiOTP\.\users\ppetrov.db for user ppetrov does not exist
LOG 2022-10-27 06:02:52 error Client-Server Error: Host answers with the following error code: 70 (ERROR: Server authentication error)
21 *ERROR: User doesn't exist
```

To solve the problem, on the server where the CredentialProvider is installed, copy the user.db file from the MultiOTP server. This is fine?
```
C:\Program Files (x86)\multiOTP>multiotp.exe -display-log -log -debug ppetrov 503307
LOG 2022-10-27 06:04:37 error Client-Server Error: Host answers with the following error code: 70 (ERROR: Server authentication error)
LOG 2022-10-27 06:04:37 debug Debug Debug: **New configuration value to write in stat for anonymous_stat_last_update: '1666843477' (was '0' before)
LOG 2022-10-27 06:04:37 debug Debug Debug: **New configuration value for anonymous_stat_last_update: '1666843477' (was '0' before)
LOG 2022-10-27 06:04:37 debug Debug Debug: **Writing configuration data not needed (no change)
LOG 2022-10-27 06:04:37 debug Debug Debug: **New stat value for anonymous_stat_last_update: '1666843477' (was '0' before)
LOG 2022-10-27 06:04:37 debug Debug Debug: **Writing stat data needed
```

```
logs from the MultiOTP server:
multiotp 5.9.3.1
Your script is running from C:\OTP\windows\
2022-10-27 10:07:12	debug		CredentialProviderRequest	Info: *Value for IsCredentialProviderRequest:	0	APP-OTP-01
2022-10-27 10:07:12	debug		Server-Client	Info: *CheckUserExists server request for ppetrov with challenge Q^@2=KRzh 5z"; EJt`:cqn@Dnbf-(a[	0	APP-OTP-01
2022-10-27 10:07:12	debug		Server-Client	Info: *CheckUserExists intermediate error code: 70	0	APP-OTP-01
2022-10-27 10:07:12	debug		Server-Client	Info: *Server secret used for command CheckUserExists with error code result 70: secretOTP	0	APP-OTP-01
========================================
multiotp 5.9.3.1
Your script is running from C:\OTP\windows\
2022-10-27 10:07:13	debug		CredentialProviderRequest	Info: *Value for IsCredentialProviderRequest:	0	APP-OTP-01
2022-10-27 10:07:13	debug		Server-Client	Info: *ReadUserData server request for ppetrov	0	APP-OTP-01
2022-10-27 10:07:13	debug		Server-Client	Info: *Server secret used for command ReadUserData with error code result 70: secretOTP	0	APP-OTP-01
========================================

```

**Comment by multiOTP** [comment]
Hello,
Be sure to have the same shared secret on the "multiOTP open source server" and on the "multiOTP CredentialProvider" computer.
The default shared secret for multiOTP open source server is **ClientServerSecret**.
When this is done, a cache file will be created on the "multiOTP CredentialProvider" when you successfully authenticate.
Best regards,

**Comment by ejikoff** [comment]
Checked the secret both on the server and on the client

**Comment by ejikoff** [comment]
In the first post logs from the test environment. But the same problem in production. When the first time I installed the multiOTP server in a production, everything worked for the first time. But at some point, users began to complain that the one-time code does not accept. After reinstalling the multiOTP server, everything worked again and after a while there were problems with the OTP code again

**Comment by multiOTP** [comment]
> Checked the secret both on the server and on the client

Be sure to never copy the users flat-files from the server to the client, because the encryption is diffenret for each installation. If you did it, please jsut delete the users flat-files on the client side (were multiOTP Credential Provider is installed).

Could you please send us your two "multiotp.ini" files (from both the server and the client), because error 70 means that the secrets used on both side are not the same !

Warning, the server_secret is encrypted in the multiotp.ini file, and the encryption key is different for each installation. If you are changing the server_secret by hand in the configuration file directly (instead of using the command line `multiotp -config server-secret=ClientServerSecret`), you have to be sure to use the **unencryted** format:

**Encrypted format** (using `:=` notation)
`server_secret:=XxXxXxXxXxXxXxXxXxXxXxXx` (server side)
`server_secret:=YyYyYyYyYyYyYyYyYyYyYyYy` (client side)
  
**Unencrypted format** ( using `=` notation, encryption will be done automatically during next changes done by multiOTP) :
`server_secret=ClientServerSecret` (server side)
`server_secret=ClientServerSecret` (client side)

Regards,

**Comment by multiOTP** [comment]
Now, it seems that your multiOTP Credential Provider installation is no more contacting the multiOTP server.
In order to install multiOTP Credential Provider on the "client" side, you need to use the MSI installer for that, because the configuration is stored in the registry **HKEY_CLASSES_ROOT\CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}**.
When you are trying to log in using the multiOTP Credential Provider, the configuration information are taken from informaiton into the registry HKEY_CLASSES_ROOT\CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}.
When you launch multiotp.exe by hand, the configuration information are taken from the multiotp.ini file, which is for sure not the same information (and not the good one).
Using directly multiotp.exe by hand, beside doing some debug, is not needed and is different than using multiOTP Credential Provider.
Regards,

**Comment by multiOTP** [comment]
1. Install multiOTP open source server on your server (or use the fully working HyperV (https://download.multiotp.net/hyper-v/) or VMWare/OVA (https://download.multiotp.net/ova/) or appliance)
2. Set a new admin password, create your user(s)
3. Install multiOTP Credential Provider on your client(s) from https://download.multiotp.net/credential-provider/ and configure the options accordingly, with the "ClientServerSecret" shared secret and the URL of the multiOTP open source server
4. When you try for the first time a connection with a user which has never been used, a local cache file will be automatically created on the client side if the authentication is successful.
Regards,

**Comment by multiOTP** [comment]
If it still doesn't work, please send us to **info - at -multiotp.net**:
1. The fully registry export of the Key `HKEY_CLASSES_ROOT\CLSID{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978`
2. The `multiotp.ini` file of the multiOTP open source server
3. The `multiotp.ini` file of the multiOTP Credential Provider
4. Regards,

**Comment by multiOTP** [comment]
Hello,
 
On the **server side,** with the open source edition, there is no automatic schedule to create the users based on the AD/LDAP. You have to schedule that every hourr for example, or launch it manually: `C:\OTP\windows\multiotp -ldap-users-sync`
 
On the **server side**, after AD/LDAP syncrhonisation, you should be able to display the QRcode for the users that have been created by the synchronisation (they are in the group "2FAUsers" you specified).
 
Now, you should be able to log-on with "viktor" on the **client side**
 
Regards,

**Comment by ejikoff** [comment]
Thanks, everything is working now!
When updating the multiotp server, do users need to scan the gr-code again?

**Comment by multiOTP** [comment]
You're welcome.
No, the users do not need to scan the qr-code again during after a multiOTP update.
Best regards
