### ISSUE TITLE
OTP when no user was established

### ISSUE THREAD

**Issue by johnamostan** [multiOTP/multiotp#155]
Hi, 

Good day. I installed multiOTPCredential on my Windows 10 machine without creating a user (local install). I am now stuck on my login screen requesting an OTP. Would there be a way for me to create a user or feed in the correct OTP?

Thank you very much for your help!

**Comment by multiOTP** [comment]
Hello, johnamostan,
This is a [multiOTP Crendential Provider](https://github.com/multiOTP/multiOTPCredentialProvider) issue.
Unfortunately, as it is a security component, there is no way to trick the system to bypass the OTP. You will have to boot your machine in recovery mode in order to remove the Credential Provider.
The safer step for the first instalaltion is to select "remote only" for the 2FA, this way, you can check the OTP process using RDP, and if everything is ok with your account, you can go further with "remote + local" protection.
Regards,
Andre

**Comment by johnamostan** [comment]
This is well noted, and apologies for putting it in this thread. I'll try that one out. thanks for the help @multiOTP!

**Comment by multiOTP** [comment]
You,re welcome, it is the same team, but we try to be clear for the GitHub users, and we separate the two projects.
regards,
