### ISSUE TITLE
MutliOTP Credential Provider works on 1 but not another server

### ISSUE THREAD

**Issue by JeroenTuinstra** [multiOTP/multiotp#158]
Installed MultiOTP server with listening port 8112. Then proceeded to install MultiOTP Credential Provider on one server, and it works like a charm. Then installed it on a second server (in the same vlan as the MultiOTP server and the 1st server) and it does not work. It asks for the login name (like the 1st server) and then at the next screen it asks for the OneTime Password, but when I enter the One Time Password (from Google Authenticator) which works on the 1st server - it now says: "Wrong one-time password"

This happens real fast. With the first server you see "connecting", but with the 2nd server it goes right away to the error. 

Any help would be appreciated.

**Comment by multiOTP** [comment]
Hello,
What did you install exactly, and where ?
Where is the multiOTP open source server installed (name of the machine) ?
Where is the first multiOTP Credential Provider installed (name of the machine). Is it the same one ?
Where is the second multiOTP Credential Provider installed (name of the machine) ?
multiOTP Credential Provider is using https connection in order to validate the authentication. Is the access to the 443 port allowed for your second server ?
Regards,

**Comment by multiOTP** [comment]
Please follow this issue on the multiOTP Credential Provider issue : https://github.com/multiOTP/multiOTPCredentialProvider/issues/83.
