### ISSUE TITLE
user without 2fa "ERROR: Invalid algorithm" - concurrent access issue

### ISSUE THREAD

**Issue by dwisdom896** [multiOTP/multiotp#166]
I have a user that is used by our oxidized system to archive configs on our switches/routers etc. 

I have added the user with a prefix of the password and picked yes require prefix, however after about 24h the user stops working with this message:

User Error:  algorithm is unknown
23 *ERROR: Invalid algorithm

I can make it work without the prefix password, however it lets any user with that name in,  Is there a way to do what I am trying to do?  

thanks!

**Comment by dwisdom896** [comment]
I am using the current version of the appliance image (multiOTP 5.9.0.1 2022-05-19) but also experienced this issue with the docker container.

**Comment by multiOTP** [comment]
Hello,
Could you give us a little bit more context ?
How are you defining the user in the multiOTP appliance ?
It seems that the (file based ?) database of the user is corrupted after 24 hours, because "User Error: algorithm is unknown" means that the algorithm define in the user database is unknown.
Rregards,

**Comment by dwisdom896** [comment]
I am creating the user thru the web interface, I put the username and put prefix as the password the user needs, and pick without2FA under token type and hit add user.

**Comment by multiOTP** [comment]
Let's say the name of the user you have create is "**oxid**"
Could you please check the content of the /etc/multiotp/users/**oxid**.db after you have created the user (you should have a line algorithm=**without2fa** in this file), and check the same file after 24 hours when it didn't work anymore with the "Invalid algorithm" error. What is the content of the file when it works, and when it doesn't ?
Regards,

**Comment by dwisdom896** [comment]
after 24h the algorithm line is changing to blank.

**Comment by dwisdom896** [comment]
It is also editing more fields like adding a token to the user, I can email you the db file before and after if that helps?

**Comment by multiOTP** [comment]
Hello,
can you please send us to info[at]multiotp.net the three following files :
user db file juste after creating the user
user db file just after successfull authentication
user db file after 24h when it's not working anymore

Do you have some kinf of user synchronization ?

Best regards

**Comment by dwisdom896** [comment]
db files are sent, we are not running any user syncronization at all either.

**Comment by multiOTP** [comment]
Hello thanks.
Which file is the file juste after creating the user ?

Best regards.

**Comment by multiOTP** [comment]
Hello,

As you can see in the three files, the create_time is different each time, which should NOT be the case, as the oxi.db backend file is never deleted by the server (unless the user is deleted).

 * oxi_working : create_time=1682962694 (the file has been created on Monday 1 May 2023 17:38:14 GMT), with a specific user_pin (user_pin:=RHFvakJ9b0goIg==), the last successful login has been done at last_login=1682962738 (Monday 1 May 2023 17:38:58 GMT)
 * oxi_broke : create_time=1683028685 (the file has been re-created on Tuesday 2 May 2023 11:58:05 GMT), without any valid information (like algorithm,  request_prefix_pin flag, user_pin, etc.) and the last failed login has been done at last_failed_time=1683040072 (Tuesday 2 May 2023 15:07:52 GMT)
 * oxi_after_fail : create_time=1683289846 (the file has been re-created again on Friday 5 May 2023 12:30:46 GMT) , without any valid information (like algorithm,  request_prefix_pin flag, user_pin, etc.), and the last failed login has been done at last_failed_time=1683295704 ( Friday 5 May 2023 14:08:24 GMT)

It seems that something like an antivirus or whatever external is emptying and/or refusing partially access to the oxi.db file. We say emptying and not deleting, because if the file was completely deleted, it would simply say "ERROR: User doesn't exist", but here, multiOTP is fixing any missing data with default values, and writing back the file.

With a file based backend, when multiOTP is called to handle a function for the user called "username", the default values for a user are set, the "username".db file is read and all contained values are set, the function (like checking the prefix) is done, all changed values are set, and the file "username".db is written back on the disk.

Does this explanation help you to find the process that should cause such an issue ?

Do you have this problem only with users having "without2fa" tokens, or do you have also this problem with others users (with TOTP or HOTP tokens) ?

Regards,

**Comment by multiOTP** [comment]
After rethinking about your ticket, we think we have a clue !
As you are using the oxi account with automated tasks, we suspect that you may have some concurrent actions for the user oxi at a certain time.
When are you doing authentication using the oxi user ? For all device at a certain time, randomly but you have a lot of devices using the same oxi account, etc. ?
Thanks to keep us in touch, and we will try to do a patch that will support the usage of the same user for a lot of automated devices.
Regards,

**Comment by dwisdom896** [comment]
It is automated however it does one device at a time, never concurrent.  There is no antivirus etc running on it, its you guys stock open source appliance image and i have had the docker container do it as well,  this does seem specific to without2fa users.  I can authenticate at any time with no issues.

**Comment by multiOTP** [comment]
Hello,
Same user concurrent access (like for automated "without2fa" tokens) is now fixed since version 5.9.6.1 (source available here : **https://github.com/multiOTP/multiotp**, docker image updated : **multiotp/multiotp-open-source:latest**)
Thanks to keep us in touch
Regards

**Comment by dwisdom896** [comment]
I have updated the container and will report back in 24-36 hours

**Comment by multiOTP** [comment]
You're welcome
