### ISSUE TITLE
Client/Server setup 5.0.3.7

### ISSUE THREAD

**Issue by agoree407** [multiOTP/multiotp#17]
Hello, I'm been trying to follow the "HOW TO CONFIGURE MULTIOTP TO USE THE CLIENT/SERVER FEATURE ?" section of the Readme file and am running into the exact same issue as the person in this forum post:  http://forum.multiotp.net/discussion/27/server-client-trouble (I'm not able to register to the forum for some odd reason, the Facebook registration doesn't appear to work, and my email request to have an invitation sent goes unanswered).

Basically, I run the webservice_install.bat as administrator and get sent to the GUI on http://localhost:8112 through which I create a user "wintest."  I use the QR code generated to add an entry in Google Authenticator.  I then test the user via the GUI's "Check a user" link, which indeed succeeds using the OTP generated by Google Authenticator.

I then (still on the server), run the following from and administrator command prompt:
```
.\mulitotp.exe -config server-secret=<secret>
.\multiotp.exe -config server-cache-level=1 server-cache-lifetime=15552000
.\multiotp.exe -debug -display-log -log wintest <token>
```
which completes successfully.

I then go to the client and run the following:
```
.\multiotp.exe -config server-secret=secret
.\multiotp.exe -config server-cache-level=1
.\multiotp.exe -config server-timeout=5
.\multiotp.exe -config server-url=http://<IP-of-server>:8112
.\multiotp.exe -debug -display-log -log wintest <token>
```

This gives me:
```
LOG 2017-04-27 20:50:54 debug Debug Debug: *parameter(s) received: -debug -display-log -log wintest 002770
LOG 2017-04-27 20:50:54 warning System Error: database file C:\Users\Administrator\Downloads\multiotp_5.0.3.7\windows\users\wintest.db for user test does not exist
LOG 2017-04-27 20:50:54 error Client-Server Error: Host answers with the following error code: 70 (ERROR: Server authentication error)
21 *ERROR: User doesn't exist
```

The debug output strikes me as weird, as why would it be complaining about the db file on the client, when it's supposed to get that info from the server?  
What's more, is that if I take the 'wintest.db' file from the server and manually place it in the directory that is being complained about on the client, everything works fine.

**Comment by agoree407** [comment]
I do have wireshark pcaps (available upon request), which may indicate this is something server-side.  The server appears to return 200 OK, while not actually sending the client anything, which in turn causes the "User does not exist" error on the client.

**Comment by multiOTP** [comment]
Hello, the new 5.x edition will be tested with this exact configuration and released next week. Have a nice day

**Comment by multiOTP** [comment]
Hello, 5.0.4.6 is available here currently : http://download.multiotp.net/
Have a look and keep us in touch
Regards,
Andre

**Comment by SunChero** [comment]
runing 5.0.4.8 .. and have the same issue .. seems like multiotp will always check local users and wont ask the server for users

**Comment by multiOTP** [comment]
The line in your log file "LOG 2017-04-27 20:50:54 error Client-Server Error: Host answers with the following error code: 70 (ERROR: Server authentication error)" means that the client try to talk to the server, but the authentication is wrong. Can you double check your secret on both side, without extra spaces ? The web service is reachable and is a multiOTP service, otherwise you should receive a 99 error code.
When the authentication cannot be done correctly, the user on the server cannot be checked/synchronized/cached to the local client.
Thanks to keep us in touch.
Regards

**Comment by Garoun** [comment]
As an additional note, I noticed having certain DOS escape characters (http://www.robvanderwoude.com/escapechars.php) can make your server-secret act a little wonky, since they can end up changing your string (^ caused many headaches). 

@SunChero @agoree407 
A quick check for the `error code: 70 (ERROR: Server authentication error)`
- [ ] Open the <multiotp root>\config\multiotp.ini config on the server and client
- [ ] Verify the encrypted _server_secret_ values match
- [ ] If they don't, copy the value from server to client and try again

I'd also suggest restricting your secret to a long string of letters and numbers, if it isn't already.
