### ISSUE TITLE
Authentication Issue with MultiOTP, RADIUS, and AD Password Prefix for CHAP Protocol

### ISSUE THREAD

**Issue by Hossam16** [multiOTP/multiotp#175]
# Issue Description

## Problem
I am encountering an issue when attempting to sync users from Active Directory (AD) and enabling them using the AD password as a prefix in MultiOTP. Specifically, the issue arises when I request access through the RADIUS protocol with PAP, which sends the password (prefixed with [AD password] + OTP) as plain text. In this scenario, authentication is successful. However, when I change the protocol to CHAP, MSCHAP-v1, or MSCHAP-v2, authentication fails, and an error message is returned, stating: "ERROR: Authentication failed (and other possible unknown errors)."

## Desired Configuration
I need to configure MultiOTP in a way that allows me to use MultiOTP in combination with RADIUS, CHAP, Active Directory (AD), and utilize the AD password as a prefix for authentication.

## Additional Information
Please provide guidance on how I can achieve this desired configuration and resolve the authentication issues when using CHAP or other secure protocols in combination with MultiOTP and AD.

Any assistance or insights into this issue would be greatly appreciated.

Thank you.

**Comment by multiOTP** [comment]
Hello,

What is the device that you want to authenticate on multiOTP using RADIUS ?

Please note that you CANNOT authenticate using a concatenated field (AD password + OTP) with a hashing algorithm, because we cannot separate the two concatenated information to be check on one side by the AD server, and on the other side on the multiOTP server.

CHAP and other hashing algorithms can be used with a concatenated field with multiOTP local prefix (multiOTP local prefix + OTP), because multiOTP can re-create and check the hash internally.

If your device is for example a FortiNet firewall (and a lot of other devices), you can say that the first authentication step is done using the AD/LDAP server, and the second OTP step is done with multiOTP server, and the multiOTP server can be synced with the AD/LDAP server to have the same accounts available.

Best regards,

**Comment by Hossam16** [comment]
Thank you for your response and for clarifying the authentication process with multiOTP using RADIUS. Your explanation about the limitations and the suggestion to use multiOTP local prefix with hashing algorithms are greatly appreciated.

Best regards,
