### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by cbaptista** [multiOTP/multiotp#176]
Hi all,

Is there any documentation about the REST API ?
And, may be this isn´t the right place to ask, how can I register at forum.multiotp.net ? How can I get an invitation code?

Thanks

**Comment by multiOTP** [comment]
Hello cbaptista,

**SOAP WSDL API**
If you are talking about the SOAP WSDL API, it's documented in https://github.com/multiOTP/multiotp/blob/master/multiotp.wsdl, and you can also check the source code of the server at https://github.com/multiOTP/multiotp/blob/master/multiotp.server.php (search _*** SOAP SERVER ***_). It's based on openotp SOAP WSDL API.

**XmlServer**
If you want to authenticate using XML post, to the integrated XmlServer, you can check the source code at https://github.com/multiOTP/multiotp/blob/master/multiotp.class.php (search _function XmlServer($data)_).

**Basic Ajax server**
Finally, if you want to use the provided Ajax server in order to create your own frontend, you can check the source code at https://github.com/multiOTP/multiotp/blob/master/multiotp.server.php (search _* Basic Ajax server *_). You will have to post the **method** and the **options** as POST or GET parameters.

To receive an invitation for the forum, you just have to send us a request by email to info@multiotp.net.

Best regards,

The multiOTP team
