### ISSUE TITLE
can a tcp socket pass credentials to a credential provider with an implemented tcp socket server? 

### ISSUE THREAD

**Issue by comsyspro** [multiOTP/multiotp#195]
i want to solve a problem when connecting to a windows computer with vnc or any other remote control software. here the problem is that you normally have to type the password by hand and if you have a long and secure password this should be better automated. so i got the idea to use a tcp socket which should connect to a tcp server which should be implemented in the credential provider code. the tcp server should then receive the username and password and then do the automated login. is this possible to implement such a tcp socket in the credential provider and can the credential provider take the username and password for an automated login?

**Comment by multiOTP** [comment]
Hello,
Yes, you could try to implement this, but the security could be a problem, because if someone else is also trying to access to the server at the same time, it could automate the login/password of session #2 with session #1.
It will be much better to use a password manager like KeePass where you can configure plugin in order to send username and password, without typing them.
Regards,

**Comment by comsyspro** [comment]
we can circumvent this by using a VPN connection. or also implement a secure socket server, the only question is in which file you should implement the socket code which waits to receive the login credentials from the socket client ond when the credentials are recived how to so the autologn step? can you give some starting hints?

**Comment by comsyspro** [comment]
yes , you are right and i also have developed an automation script which also works well. but i also want to look into an alternative method. it's good to know that it's somehow possible with a credential provider i only have to find out how to do it.
