### ISSUE TITLE
Allow Sync of both UPN and SAMAccountName

### ISSUE THREAD

**Issue by iitahhydes** [multiOTP/multiotp#200]
Can the code be updated to allow the sync of both UPN and SAMAccountName to MultiOTP, if you modify the username.db file for the user to add their UPN it works with either UPN or SAMAccountName. There are times where the preferred logon for certain accounts would be UPN but others might be SAMAccountName

**Comment by multiOTP** [comment]
Hello,
Currently, it must be the same authentication for all users, UPN or SAMAccountName. This is because the authentication field is the primary key (which is the name of the file in case the backend is file based), and in the case of a backend file based, we don't want to parse every user file in order to find a second authentication method.
We will think about implementing an alias method, but this should be scalable as we support also client/server installation.
Regards,
