### ISSUE TITLE
Possible to configure user without OTP-login

### ISSUE THREAD

**Issue by kristianwh** [multiOTP/multiotp#40]
Hi, thanks for a great piece of software!

I have one issue: I would like only some of my users to login with OTP-key.
The rest of the users should be able to login with just username / password, as usual.

I tried simply not adding the user in the multiotp web interface, but I still get the OTP login window, and cannot login. Is there any way to achieve this? Adding a "None" option for "Token type" or in the "Select a token" dropdown in the web interface, perhaps?

Edit: I use the multiOTPCredentialProvider on Windows 10 (planning to use on Windows Server 2016).

**Comment by multiOTP** [comment]
Hello,
thanks for using our product. We have added your suggestion in our roadmap.
Your ticket will be updated when this will be implemented.

**Comment by kristianwh** [comment]
Great, thanks!

**Comment by multiOTP** [comment]
Hello Kristian,
This option has been added in version 5.3.0.0 (https://github.com/multiOTP/multiotp/releases/tag/5.3.0.0)
A new "without2fa" token algorithm is now available.
Thanks a lot for your feedback. If you want to continue to support our work with a small donation, have a look at the Wiki homepage, we provide a link to our Paypal account.
Regards,
Andre

**Comment by kristianwh** [comment]
Thank you, that was fast! I tried the new functionality - deleted and readded a user and changed the algorithm to without2fa. Tried to login again, but I am still asked to input 2FA-code. Am I doing something wrong? I unregistered the credentials provider and installed the 5.3.0.0 version also, but the problem remains.

**Comment by multiOTP** [comment]
Hello Kristian, 
 
Sorry about that, without2FA is implemented in the open source library since 5.3.0.0, but everything is working fine in the multiOTP Credential Provider since 5.3.0.3 only. The various tests passed successfully.
 * https://github.com/multiOTP/multiotp/tree/5.3.0.3
 * https://github.com/multiOTP/multiOTPCredentialProvider/tree/5.3.0.3
 
Please check it on your side and close this issue if it is resolved. 
 
Thanks a lot for your feedback. If you want to continue to support our work with a small donation, have a look at the Wiki homepage, we provide a link to our Paypal account. 
 
Regards,
Andre

**Comment by kristianwh** [comment]
Great, I'll try it out. Thanks!

**Comment by kristianwh** [comment]
Hi, I have tested, but when I'm installing the 5.3.0.3 version of the credential provider, I get the following test result during the configuration test:
multiOTP test result: Authentication failed (and other possible uknown erro
Credential Provider stare: not activated

I have added two users, one with TOTP and one with the new without2FA. Tried both, but none of them worked during this test. When I test in the web interface (Check user), both users return test result 'Succeeded'.

**Comment by Storck1** [comment]
Hi,
i tryied to install the MultiOTP web server on a Windows 2016 server with 2 client (one W10 and one W7).
The server is working fine with my AD (got my LDAP sync with the AD group i set)
But when i try to install the 5.3.0.3 version of the credential provider on my client, i got the same error than @kristianwh (multiOTP test result: Authentication failed (and other possible uknown erro
Credential Provider state: not activated)

i have already try to reinstall my server twice but the problem is still there.
any clue ?

Regards

Arnaud

**Comment by multiOTP** [comment]
Hello Kristian,
we have published a new 5.4.0.1 version of multiOTP which should correct the issue.
Could you give it a try and let us know if it's ok now ?
Best regards

**Comment by kristianwh** [comment]
Thank you, now it works great!
