### ISSUE TITLE
How to compile the sources?

### ISSUE THREAD

**Issue by xyu3xx** [multiOTP/multiotp#5]
I made any changes in sources but i dont know how to compile, can you help?

**Comment by multiOTP** [comment]
Hello,
Can you please be more precise. What did you change? What do you want to compile, for which version ?
Best regards,
Andre

**Comment by xyu3xx** [comment]
I had some problems when i used the command to synchronize with the active directory. Your software
its synchronizing only some users, so i modified the source code to make it work. I would like to compile, but i had no success with softwares like ExeOutput, EXE-P, Bambalam PHP EXE, among others. I wonder how you compiled the source code.

**Comment by multiOTP** [comment]
Hello,
What was the problem with the AD synchronization ? And what is the problem with the "compilation" softwares you use ?
As for LGPL projets, thanks to provide the patch to the community. We will do the compilation for you, as we are signing digitally the executable.
Depending your modifications, it could be possible that some stuff is not directly compatible with tools like ExeOutput or Bambalam,
As soon as your modifications are working with our executable creation process, we will give you the step to step procedure used to do the "compilation".
Best regards
Andre

**Comment by multiOTP** [comment]
Any feedback from your side @xyu3xx on what to correct for the next release ? IN order to create the Windows EXE file, we used Bambalam PHP EXE up to version 4.3.0.0.
Currently, we are using the phc-cli compiler which supports PHP 5.3.1, and everything is then packed in a virtual application (using BoxedApp, Enigma or similar) in a single EXE.
