### ISSUE TITLE
Get approval request via authenticator app

### ISSUE THREAD

**Issue by qzem** [multiOTP/multiotp#64]
I wonder if it is already possible to configure MultiOTP to send authentication approval request to your authenticator app on phone? Similar as google 2FA or microsoft office 365 MFA works. For example, when I try to sign in in one of the google web services I enter password and then I also get an approval request via authenticator app on phone, than I just press approve on my phone and I am in. It is secure an much more simple, than always typing OTP.

If it is not possible I would appreciate if you'll put this on a wish list.

Thank you!

Kind regards,
 Q

**Comment by multiOTP** [comment]
Hello Q!

No, this is not possible, as our library is primarly done to be compatible with radius based authentication. Furthermore, for security reasons, our library doesn't require any Internet connexion in order to work. Finally, interaction with a mobile phone will require to subscribe for a cloud based notification system and to develop a specific authentication app.

We are keeping your idea in a wish list.

Best regards,

A.

**Comment by qzem** [comment]
Thank you for your answere.

**Comment by multiOTP** [comment]
Have a look at issue https://github.com/multiOTP/multiotp/issues/54 ;-)
