### ISSUE TITLE
docker image system requirements 

### ISSUE THREAD

**Issue by wjohnston-sfdc** [multiOTP/multiotp#70]
I am executing the docker image and am having trouble starting it. First i saw that the image was running out of space

```
docker run --mount source=multiotp-data,target=/etc/multiotp -p 80:80 -p 443:443 -p 1812:1812/udp -p 1813:1813/udp -d multiotp/multiotp-open-source
```
```
# docker logs f27eb19bf2ea
/boot/newvm.sh: line 132: dmidecode: command not found
Stopping FreeRADIUS daemon: freeradius/var/run/freeradius/freeradius.pid not found....
/boot/newvm.sh: line 245: /etc/iptables/rules.v4: No such file or directory
/boot/newvm.sh: line 247: /etc/iptables/rules.v6: No such file or directory
Creating a new multiotp.ini file
Zeroing disk space...
dd: error writing '/zeroes': No space left on device
```

So i increased the space.

The CPU seems a bit over taxed now. Can you point me the the minimum requirements for the docker image?

thank you
-winn

**Comment by th3-w1ll** [comment]
there seems to be a problem in raspberry/boot-part/newvm.sh

the detection of the type docker won't succeed.
you have to build a custom docker image
I've set 

TYPE=DOCKER
before
# Docker backend is forced to be files
if [[ "${TYPE}" == "DOCKER" ]]; then
    BACKEND="files"
fi

then everything seems to work fine.

Better way is to find out why normal type detection won't work

**Comment by mchubby** [comment]
> Better way is to find out why normal type detection won't work

Try to `docker exec -it containerid /bin/bash` and check the `uname -a` result. containerid of the running container is obtained using `docker ps`.

Otherwise, trace the script execution when building from the Dockerfile using
`ENV SHELLOPTS xtrace`
I had to rely on the `raspberry/boot-part` tree, imported from the release zip, no idea how that hierarchy is generated.

For instance, WSL2-based backend for Docker desktop yields "`Linux 7cc4f0615ffe 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 GNU/Linux`" (may differ based on which .MSI kernel update is currently installed, I suppose).

**Comment by multiOTP** [comment]
Docker detection has been improved in version 5.8.0.3, which will be released 2. October.
