### ISSUE TITLE
Account lockout is not working

### ISSUE THREAD

**Issue by arddg** [multiOTP/multiotp#73]
Hi!
I'm using multiOTP on Ubuntu 18.04 for l2tp and sstp vpn with OTP value as a user's password.
After several unsuccessful authentication attempts user account is not locked. Only active directory account is locked, but not multiotp's.
Is it a normal behavior?

I have these setting in multiotp.ini:
failure_delayed_time=300
max_block_failures=6
max_delayed_failures=3

**Comment by multiOTP** [comment]
Hi,
If you try ti make unsuccessful authentication always with the same false OTP, it will count only as one trial ? Why ? Because we a lot of VPN clients, it will try several times to connect with the same user/pass if the first connection is not working, and this coulddisable your account at the first trial.
Regards,

**Comment by arddg** [comment]
No, I have tried different OTPs each time I connect. But after 10 unsuccessful attempts only AD account is locked, but not miltiOTP's. I'm using mschapv2 if it matters.

**Comment by arddg** [comment]
Sorry, it seems I had a wrong understanding how does lockout policy work. It works actually! It became much clearer to me after reading the log file :)
Thanks!
