### ISSUE TITLE
Token increase time interval 

### ISSUE THREAD

**Issue by selvakumar89** [multiOTP/multiotp#9]
Hi,
The token time interval by default taking 30 sec. how to increase it. Help me please.

**Comment by sunojvijayan** [comment]
Anyone knows how to do it?

**Comment by multiOTP** [comment]
Hello, what's the exact question, because the time interval must be synchronized with your token generation time interval (the token code is based on this time step).
What do you want exactly to do ?
Regards,

**Comment by selvakumar89** [comment]
Hi,

Thank you for the prompt response. Essentially, I would like to increase the time validity window from the default 30s to 60s.

**Comment by multiOTP** [comment]
Hello,
Don't be confused, the time interval of the token (most of the time 30 seconds) is NOT the time validity window, which is 600 seconds by default and can be changed like this:
multiotp -config max-time-window=999
or directly in the multiotp.ini, search for max_time_window= and change th value
Regards,

**Comment by selvakumar89** [comment]
Thanks. I got it now.
My question is here is it possible to change the time interval from 30 seconds to 60 seconds?

**Comment by multiOTP** [comment]
Yes, but please explain clearly what you want to do, and with which kind of tokens you want to work, because the token MUST also have the same time interval in the algorithm, otherwise the authentication will not work.

### Check the integrated help (multiotp -help)
Create _alan_ account with a TOTP software token that has 60 seconds time interval, 6 digits and the prefix pin enabled:
multiotp -debug -create -prefix-pin alan TOTP 3683453456769abc3452 2233 6 60
